server {
    listen 80;
    listen [::]:80;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name fat-tata.cdbzzy.cn;
    root /srv/tata-h5/fat/h5;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/fat-tata.cdbzzy.cn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fat-tata.cdbzzy.cn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-fat-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name fat-tata-admin.cdbzzy.cn;
    root /srv/tata-h5/fat/admin;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/fat-tata.cdbzzy.cn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fat-tata.cdbzzy.cn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-fat-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name tata.cdsparkling.cn;
    root /srv/tata-h5/prod/h5;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name tata-admin.cdsparkling.cn;
    root /srv/tata-h5/prod/admin;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}
