server {
    listen 80;
    listen [::]:80;
    server_name tcfzyq.online;
    root /srv/tata-h5/tcfzyq/current/h5;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-fat-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name admin.tcfzyq.online;
    root /srv/tata-h5/tcfzyq/current/admin;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-fat-routes.conf;
}
