server {
    listen 80;
    listen [::]:80;
    server_name www.tata.tcfzyq.online;
    root /srv/tata-h5/production/current/h5;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-production-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name tata-admin.tcfzyq.online;
    root /srv/tata-h5/production/current/admin;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-production-routes.conf;
}
