server {
    listen 80;
    listen [::]:80;
    server_name tata-test.cdsparkling.cn;
    root /srv/tata-h5/test/h5;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name tata-admin-test.cdsparkling.cn;
    root /srv/tata-h5/test/admin;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name tata.cdsparkling.cn;
    root /srv/tata-h5/production/h5;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name tata-admin.cdsparkling.cn;
    root /srv/tata-h5/production/admin;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}
