server {
    listen 80;
    listen [::]:80;
    server_name fat-tata.cdsparkling.cn;
    root /srv/tata-h5/fat/h5;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name fat-tata-admin.cdsparkling.cn;
    root /srv/tata-h5/fat/admin;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name tata.cdsparkling.cn;
    root /srv/tata-h5/prod/h5;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name tata-admin.cdsparkling.cn;
    root /srv/tata-h5/prod/admin;
    index index.html;

    include /etc/nginx/snippets/tata-static-security.conf;
    include /etc/nginx/snippets/tata-static-routes.conf;
}
